# After any modifications to this file, be sure to check it with
# http://lint.travis-ci.org/

language: python
python:
    - 3.3
    - 2.7
env:
    - DJANGO_VERSION=1.5.1
    - DJANGO_VERSION=1.4.5
install:
    - pip install --use-mirrors Django==$DJANGO_VERSION
    - python setup.py -q install
script: django-admin.py test portfolio --settings="portfolio.tests.settings"
